/* TSQL É UM BLOCO DE LINGUAGEM DE PROGRAMACAO.
PROGRAMAS SAO UNIDADES QUE PODEM SER CHAMADAS DE BLOCOS
ANÔNIMOS. BLOCOS ANONIMOS NAO RECEBEM NOME, POIS
NAO SAO SALVOS NO BANCO. CRIAMOS BLOCOS ANONIMOS QUANDO
IREMOS EXECUTA-LOS UMA SO VEZ OU TESTAR ALGO */

/* BLOCO DE EXECUÇÃO */

BEGIN
		PRINT 'PRIMEIRO BLOCO'
END
GO

/* BLOCOS DE ATRIBUIÇÃO DE VARIAVEIS */

DECLARE
    @CONTADOR INT
BEGIN
    SET @CONTADOR = 5
    PRINT @CONTADOR
END
GO
 
/* Clausula GO ela delimita esse comando em uma BET (Pacotinho)
que vai ser mandado para o ENGINE do SQL Server que vai processar
e executar o código, as variáveis ficam limitadas ao escopo do GO*/

/* NO SQL SERVER CADA COLUNA, VARIAVEL LOCAL, EXPRESSÃO E PARAMETRO 
TEM UM TIPO 

CAST -> É mais comum
CONVERT -> É para trabalhar com Data */

DECLARE
    @V_NUMERO NUMERIC(10,2) = 100.52,
    @V_DATA DATETIME = '20170207'
BEGIN
    PRINT 'VALOR NÚMERICO: ' + CAST(@V_NUMERO AS VARCHAR)
    PRINT 'VALOR NÚMERICO: ' + CONVERT(VARCHAR, @V_NUMERO)
    PRINT 'VALOR DE DATA: ' + CAST(@V_DATA AS VARCHAR)
    PRINT 'VALOR DE DATA: ' + CONVERT(VARCHAR, @V_DATA, 121)
    PRINT 'VALOR DE DATA: ' + CONVERT(VARCHAR, @V_DATA, 120)
    PRINT 'VALOR DE DATA: ' + CONVERT(VARCHAR, @V_DATA, 105)
END
GO

