/* MODA - MODE() WITHIN GROUP (ORDER BY COLUNA) */

/* PEGA A MODA DA COLUNA TODA - 15 */
SELECT MODE() WITHIN GROUP (ORDER BY QTD) AS "Moda"
FROM MAQUINAS;

/* PEGA A MODA DA COLUNA TODA - 15 */
SELECT MAQUINA, MODE() WITHIN GROUP (ORDER BY QTD) AS "Moda"
FROM MAQUINAS
GROUP BY MAQUINA;
