/* ORGANIZAR FISICAMENTE UM BANCO DE DADOS

1 - CRIAR O BANCO COM ARQUIVOS PARA OS SETORES DE MKT
E VENDAS
2 - CRIAR UM ARQUIVO GERAL
3 - DEIXAR O MDF APENAS COM O DICIONÁRIO DE DADOS
4 - CRIAR 2 GRUPOS DE ARQUIVOS (PRIMARY - MDF)

*/

USE EMPRESA
CREATE TABLE TB_EMPRESA(
	ID INT,
	NOME VARCHAR(50)
)
GO
