/* BULK INSERT - IMPORTAÇÃO DE ARQUIVOS */

CREATE TABLE LANCAMENTO_CONTABIL(
	CONTA INT,
	VALOR INT,
	DEB_CRED CHAR(1)
)
GO

SELECT * FROM LANCAMENTO_CONTABIL
GO

/* \t = TAB ESPAÇO, É O DELIMITADOR DE COLUNAS 
   \n = ENTER */

BULK INSERT LANCAMENTO_CONTABIL
FROM "Z:\CONTAS.txt"
WITH
(
	FIRSTROW = 2,
	DATAFILETYPE = 'char',
	FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '\n'
)
GO
