/* DESVIO PADRÃO E VARIÂNCIA */
STDDEV_POP(COLUNA)
VAR_POP(COLUNA)

SELECT MAQUINA,
	ROUND(AVG(QTD), 2) AS MEDIA,
    MAX(QTD) AS MAXIMO,
    MIN(QTD) AS MINIMO,
    MAX(QTD) - MIN(QTD) AS AMPLITUDE,
    ROUND(STDDEV_POP(QTD), 2) AS DESVIO_PADRAO,
    ROUND(VAR_POP(QTD), 2)AS VARIANCIA
    FROM MAQUINAS
    GROUP BY MAQUINA
    ORDER BY 4 DESC;
