/* FILTROS DE GRUPO */

/* FILTROS BASEADOS EM VALORES NÚMERICOS */

SELECT NOME, DEPARTAMENTO, SALARIO
FROM FUNCIONARIOS
WHERE SALARIO > 100000;


SELECT NOME, DEPARTAMENTO
FROM FUNCIONARIOS
WHERE SALARIO > 100000;

/* FILTROS BASEADOS EM STRINGS */

SELECT NOME, DEPARTAMENTO, SALARIO
FROM FUNCIONARIOS
WHERE DEPARTAMENTO = 'Ferramentas';

-- Ignora MAIUSCULAS ou minusculas
SELECT NOME, DEPARTAMENTO, SALARIO
FROM FUNCIONARIOS
WHERE DEPARTAMENTO ILIKE 'FERRAMENTAS';

/* FILTROS BASEADOS EM MULTIPLAS, TIPOS E COLUNAS - CONSIDERAR OR E AND */

SELECT NOME, DEPARTAMENTO, SALARIO
FROM FUNCIONARIOS
WHERE DEPARTAMENTO = 'Ferramentas'
AND 
SALARIO > 100000;

/* FILTRO BASEADO EM UNICO TIPO E COLUNA - ATENÇÃO PARA A REGRA DO AND E OR 

Em relacionamentos 1 x 1 o filtro and trantando de uma única coluna
sempre dará falso
*/

-- Retorna sempre FALSE
SELECT NOME, DEPARTAMENTO, SALARIO
FROM FUNCIONARIOS
WHERE DEPARTAMENTO = 'Ferramentas'
AND 
DEPARTAMENTO = 'Livros';

-- FILTROS BASEADOS EM PADRÃO DE CARACTERES
SELECT DEPARTAMENTO, SUM(SALARIO) AS "Total"
FROM FUNCIONARIOS
WHERE 
DEPARTAMENTO LIKE 'B%'
GROUP BY DEPARTAMENTO;

-- FILTROS BASEADOS E PADRÃO DE CARACTERES COM MAIS LETRAS

SELECT DEPARTAMENTO, SUM(SALARIO) AS "Total"
FROM FUNCIONARIOS
WHERE 
DEPARTAMENTO LIKE 'Be%'
GROUP BY DEPARTAMENTO;

-- UTILIZANDO O CARACTERER CORINGA NO MEIO DA PALAVRA

SELECT DEPARTAMENTO, SUM(SALARIO) AS "Total"
FROM FUNCIONARIOS
WHERE 
DEPARTAMENTO LIKE 'B%s'
GROUP BY DEPARTAMENTO;

/* E se eu quiser filtrar o agrupamento pelo salário? por exemplo, 
maior que 400000

Está filtrando por algo que não está agregada, se colocar dentro do 
WHERE uma coluna agregada, vai dar ERRO!
COLUNAS NÃO AGREGADAS - WHERE
COLUNAS AGREGADAS - HAVING
*/
SELECT DEPARTAMENTO, SUM(SALARIO) AS "Total"
FROM FUNCIONARIOS
WHERE 
DEPARTAMENTO LIKE 'B%s'
GROUP BY DEPARTAMENTO
HAVING SUM(SALARIO) > 400000;
