/* INICIANDO MODELAGEM FÍSICA */

/* CRIANDO UM BANCO DE DADOS */

CREATE DATABASE PROJETO;

/*CONECTANDO-SE AO BANCO */

USE PROJETO;

/*CRIANDO A TABELA*/

CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)
);
