/* PROCEDURE DE CADASTRO */

CREATE PROC CADASTRO @NOME VARCHAR(30), @SEXO CHAR(1), @NASCIMENTO DATE,
@TIPO CHAR(3), @NUMERO VARCHAR(10)
AS
    DECLARE @FK INT
    INSERT INTO PESSOA VALUES(@NOME, @SEXO, @NASCIMENTO) -- GERAR UM ID

    SET @FK = (SELECT IDPESSOA FROM PESSOA WHERE IDPESSOA
    = @@IDENTITY)

    INSERT INTO TELEFONE VALUES(@TIPO, @NUMERO, @FK)
GO

CADASTRO 'JORGE', 'M', '1981-01-01', 'CEL', '98734512'
GO

-- * Traz tudo de pessoa e Tudo de Telefone
SELECT PESSOA.*, TELEFONE.*
FROM PESSOA
INNER JOIN TELEFONE
ON IDPESSOA = ID_PESSOA
GO
