/* Recap */

CREATE DATABASE MAFRA;

/*Estou esntrando no Banco de Dados MAFRA para usá-lo*/
USE MAFRA;

/*Criando a tabela ALUNOS*/
CREATE TABLE ALUNOS(
	NUMERO INT,
	NOME VARCHAR(30)
);

/*Excluindo os Bancos de Dados*/
DROP DATABASE COMERCIO;
DROP DATABASE EXEMPLO;
DROP DATABASE MAFRA;
DROP DATABASE PROJETO;
DROP DATABASE TESTE;

/* PROCEDURES */

CREATE DATABASE PROJETO;

USE PROJETO;

CREATE TABLE CURSOS(
    IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	HORAS INT(3) NOT NULL,
	VALOR FLOAT(10,2) NOT NULL
);

INSERT INTO CURSOS VALUES(NULL,'JAVA',30,500.00);
INSERT INTO CURSOS VALUES(NULL,'FUNDAMENTOS DE BANCOS DE DADOS',40,700.00);

SELECT * FROM CURSOS;

DELIMITER #

STATUS

/*Criando Procedure*/
CREATE PROCEDURE CAD_CURSO(P_NOME VARCHAR(30),
						   P_HORAS INT(30),
						   P_PRECO  FLOAT(10,2))
BEGIN

    INSERT INTO CURSOS VALUES(NULL,P_NOME,P_HORAS,P_PRECO);

END
#
/*Volta o Delimiter*/
DELIMITER ;

/*Passando dados*/
CALL CAD_CURSO('BI SQL SERVER',35,3000.00);
CALL CAD_CURSO('POWER BI',20,1000.00);
CALL CAD_CURSO('TABLEAU',30,1200.00);

SELECT * FROM CURSOS;

/*Exercícios*/

/*PASSANDO MAIS DADOS*/

CALL CAD_CURSO('JAVA COMPLETO', 55, 800.00);

/* CRIAR UMA PROCEDURE PARA CONSULTAR CURSOS */
DELIMITER #

CREATE PROCEDURE CONSULTA_CURSOS(P_NOME VARCHAR(30))
BEGIN
    SELECT * FROM CURSOS WHERE NOME = P_NOME;
END
#

DELIMITER ;

STATUS

CALL CONSULTA_CURSOS('BI SQL SERVER');

/* QUANTIDADE DE HOMENS E MULHERES */
