/* QUAL A MODA DAS QUANTIDADE */

SELECT QTD, COUNT(*) AS MODA
FROM MAQUINAS
GROUP BY QTD
ORDER BY 2 DESC;

/* QUAL É O MÁXIMO E MINIMO E AMPLITUDE DE CADA MÁQUINA */

SELECT MAQUINA,
    MAX(QTD) AS MAXIMO,
    MIN(QTD) AS MINIMO,
    MAX(QTD) - MIN(QTD) AS AMPLITUDE
    FROM MAQUINAS
    GROUP BY MAQUINA
    ORDER BY 4 DESC;

/* MÉDIA */

SELECT MAQUINA,
	ROUND(AVG(QTD), 2) AS MEDIA,
    MAX(QTD) AS MAXIMO,
    MIN(QTD) AS MINIMO,
    MAX(QTD) - MIN(QTD) AS AMPLITUDE
    FROM MAQUINAS
    GROUP BY MAQUINA
    ORDER BY 4 DESC;

